In [1]:
import pandas
import os
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
import progressbar
import torch
import torchvision
import torchvision.transforms as transforms

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc3 = nn.Linear(16 * 11 * 11, 120)
        self.fc1 = nn.Linear(120, 600)
        self.fc2 = nn.Linear(600, 1000)
        
    def forward(self, x):
        x = x.view(-1, 1, 56, 56)
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 11 * 11)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
#         x = F.softmax(x, dim=1)
        return x

model = torch.load("/home/zedroman/Documents/Sonia/Ierogliph/models2/4")
model.eval()


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=1936, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=600, bias=True)
  (fc3): Linear(in_features=600, out_features=1000, bias=True)
)

In [3]:
i_height = 56
i_width = 56
import json
with open('/home/zedroman/Documents/Sonia/Ierogliph/itoc.txt', 'r') as outfile:  
    itoc = json.load(outfile)
with open('/home/zedroman/Documents/Sonia/Ierogliph/ctoi.txt', 'r') as outfile:  
    ctoi = json.load(outfile)
    
def itocf(x):
    for i in range(len(x)):
        x[i] = itoc[str(x[i].item())]
        
def ctoif(x):
    for i in range(len(x)):
        x[i] = ctoi[str(x[i].item())]
        

In [4]:
import scipy.misc

def get_data(i):
    data = "/home/zedroman/Documents/Sonia/Ierogliph/test.npy/test{}.npy".format(i)
    test = torch.from_numpy(np.load(data)).float()
    return test

In [5]:
def get_ans(model, test_ans, fr):
    test_ans = model(test_ans)
    test_ans = test_ans.data.max(1, keepdim=True)[1]
    ctoif(test_ans)
    nums = torch.arange(fr, fr + test_ans.shape[0]).reshape((test_ans.shape[0], 1)) + 1
    return(torch.cat((nums, test_ans), 1))

fr = 0
for i in range( 10):
    test = get_data(i)
    print(test.shape)
    test = get_ans(model, test, fr)
    fr += test.shape[0]
    print(test[0:3])
    import pandas as pd
    test = test.numpy()
    np.savetxt("/home/zedroman/Documents/Sonia/Ierogliph/ans{}.csv".format(i), test, fmt="%d", delimiter=",")
    print('ok')

torch.Size([8325, 1, 56, 56])
tensor([[    1, 63955],
        [    2, 65207],
        [    3, 64709]])
ok
torch.Size([8325, 1, 56, 56])
tensor([[ 8326, 61654],
        [ 8327, 60856],
        [ 8328, 63152]])
ok
torch.Size([8325, 1, 56, 56])
tensor([[16651, 60369],
        [16652, 65208],
        [16653, 61899]])
ok
torch.Size([8325, 1, 56, 56])
tensor([[24976, 59606],
        [24977, 59845],
        [24978, 65238]])
ok
torch.Size([8325, 1, 56, 56])
tensor([[33301, 61654],
        [33302, 64466],
        [33303, 62647]])
ok
torch.Size([8325, 1, 56, 56])
tensor([[41626, 62914],
        [41627, 60101],
        [41628, 61394]])
ok
torch.Size([8325, 1, 56, 56])
tensor([[49951, 62670],
        [49952, 63445],
        [49953, 60343]])
ok
torch.Size([8324, 1, 56, 56])
tensor([[58276, 64697],
        [58277, 62421],
        [58278, 59334]])
ok
torch.Size([8324, 1, 56, 56])
tensor([[66600, 62130],
        [66601, 59318],
        [66602, 59571]])
ok
torch.Size([8324, 1, 56, 56])
tensor([[74924, 